### ISSUE TITLE
Capturing still image

### ISSUE THREAD

**Issue by pnicholls** [Present-Inc/CameraKit#3]
hey @justinmakaila did you ever manage to get still image capture working? 

I noticed c9026a96f0ea3ee74c7d776dd6be2a0471b07c11

Was the problem mostly around the `cgImageFromSampleBuffer` function? Aiming to have a crack at getting this working but wanted to make sure I am on the right path first. 

Cheers!

**Comment by justinmakaila** [comment]
@pnicholls Yes, exactly. It kept crashing for whatever reason. I think it was a memory retention issue. Let me know if you get something working. I'll leave this open for discussion purposes.

**Comment by justinmakaila** [comment]
@pnicholls I'm about to take a swing at this today. Have you tried anything or ran into any issues I should be aware of?

**Comment by justinmakaila** [comment]
@pnicholls Just added support for capturing a still image. I also updated the way that it's handled in the example project to give you an idea of it's usage.

This uses a delegation pattern, but I have some plans to utilize some swift-ier features, and ReactiveCocoa. It'd be cool to get some input on how the community would like to see this develop moving forward.

See [1.2.0](https://github.com/Present-Inc/CameraKit/commit/5f35eccaafb00837b1918e41fdf2bbfa0d01a610)

**Comment by pnicholls** [comment]
Hey nice work!

I didn't get around to it yet but `AVCaptureStillImageOutput` was exactly what I was going to do. 

I think RAC stuff could be interesting (i just migrated from ReactiveCocoa to RxSwift myself) but its a pretty narly dependency to have IMO.

**Comment by justinmakaila** [comment]
@pnicholls I think we'd move it to a separate repository, using Carthage/CocoaPods for dependency version control. Probably just subclass `CameraController` to something like `ReactiveCameraController`, implement the delegate, and spit everything out onto signals

**Comment by pnicholls** [comment]
Yeah that sounds like the way to go. :+1:
